site_name: Creality K1 Wiki
site_description: База знаний по 3D принтерам Creality K1, K1 Max, K1C
site_url: https://siper.github.io/creality-k1-wiki/

theme: 
  name: material
  language: ru

nav:
  - index.md
  - Обслуживание и профилактика: care.md
