site_name: Creality K1 Wiki
site_description: База знаний по 3D принтерам Creality K1, K1 Max, K1C
site_url: https://siper.github.io/creality-k1-wiki/

theme: 
  name: material
  language: ru

nav:
  - Главная: index.md
  - Обслуживание и профилактика: care.md
  - Софт:
    - Получение Root доступа: root.md
    - Подключение к принтеру по SSH: ssh.md
    - Запуск и обновление Installation Helper Script: helperscript.md
  - Добавление информации: contribution.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences