name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install --no-deps -r requirements.txt
      - name: Build site
        run: mkdocs build --strict
      - name: Deploy pages
        run: mkdocs gh-deploy --strict --force
